require("config.colorscheme_transparency")
require("config.general_options")
require("config.general_keymaps")
require("config.general_autocmds")
require("config.status_line")
require("config.lsp")
require("config.lazy")
require("config.colorscheme_which_key")
